# Generated by Django 5.2.17 on 2026-09-25 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='contactos_autorizados',
            field=models.ManyToManyField(blank=True, related_name='cuentas_autorizadas', to='gestion.cliente'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_principales', to='gestion.cliente'),
        ),
    ]
