# Generated by Django 5.2.17 on 2026-09-25 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_cuenta_contactos_autorizados_alter_cuenta_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='creada_en',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='moneda',
            field=models.CharField(choices=[('CLP', 'Peso Chileno ($)'), ('USD', 'Dólar Estadounidense (USD$)')], default='CLP', max_length=3),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='gestion.cliente'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.CharField(choices=[('CORRIENTE', 'Cuenta Corriente'), ('VISTA', 'Cuenta Vista / Rut'), ('AHORRO', 'Cuenta de Ahorro')], default='VISTA', max_length=20),
        ),
    ]
