# Generated by Django 5.2.17 on 2026-09-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_cuenta_creada_en_cuenta_moneda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.CharField(choices=[('CORRIENTE', 'Cuenta Corriente'), ('VIRTUAL', 'Cuenta Virtual / Billetera'), ('AHORRO', 'Cuenta de Ahorro')], default='VISTA', max_length=20),
        ),
    ]
